name: todo_app_2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  http: ^1.5.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  android_intent_plus: ^6.0.0
  flutter_background: ^1.3.0+1
  flutter_foreground_task: ^9.1.0
  permission_handler: ^12.0.1
  package_info_plus: ^9.0.0
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/animations/

